### ISSUE TITLE
suggest a working scheme for this project 

### ISSUE THREAD

**Issue by xeon-zolt** [xeon-zolt/mew#1]
i am very confused on how to implement it , use bash only or use it with binary files of c then weather to use tree or a matrix its confusing me

**Comment by singh1114** [comment]
creating files would be better approach.

**Comment by xeon-zolt** [comment]
can you explain me more @singh1114

**Comment by muppathimoonu** [comment]
@xeon-zolt @singh1114 is Correct! We can simply Create files which contains commands for same operations for various Operating systems! Separate files for separate commands and the base mew will simply identify the Os and executes the Respective Commands for input!

**Comment by xeon-zolt** [comment]
@surya-yogi example

**Comment by muppathimoonu** [comment]
A separate file to install vlc. it will contain yum install vlc & apt-get install vlc etc..
mew install vlc will simply look for the file vlc and run the relevant command as per Os requirements

**Comment by xeon-zolt** [comment]
their are more packages than package managers

**Comment by muppathimoonu** [comment]
yeah!!
